const TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  EMAIL_SIGN_IN: "EMAIL_SIGN_IN",
  GOOGLE_SIGN_IN: "GOOGLE_SIGN_IN",
  LOG_OUT: "LOG_OUT",
  FACEBOOK_SIGN_IN: "FACEBOOK_SIGN_IN",
  GET_ERRORS: "GET_ERRORS",
  SET_RESULTS: "SET_RESULTS",
  SET_CENTER: "SET_CENTER",
  SET_ZOOM: "SET_ZOOM",
  GET_BUSINESS_PROFILE: "GET_BUSINESS_PROFILE",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  CLEAR_USER_PROFILE: "CLEAR_USER_PROFILE"
}

export default TYPES;